### ISSUE TITLE
Redirect undefined routes to main application

### ISSUE THREAD

**Issue by clearnote01** [NIT-Hamirpur-NITH/chatty#2]
Currently, illegal routes like 'glug.nith.ac.in:3000/abcd' gives the error 404. At production level i suppose it should redirect to the main application.

**Comment by akshendra** [comment]
@clearnote01 this was never supposed to go in production 😆

**Comment by clearnote01** [comment]
@akshendra It's a great demo for node app at least! (which i am trying to learn) :D
